# Generated by Django 4.0.1 on 2022-02-10 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_is_author_user_special_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
