# Generated by Django 3.2.12 on 2022-02-14 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_special',
        ),
    ]
